apiVersion: v1
kind: Service
metadata:
  name: {{ include "devop-service-test.fullname" . }}
  labels:
    {{- include "devop-service-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "devop-service-test.selectorLabels" . | nindent 4 }}
